openapi: 3.0.3
info:
  title: JPN-API Reference
  version: 1.0
  contact:
    name: JPN-API Support
    url: admin@jpn-cards.co
  description: >-
    Here, you will find all the necessary information to interact with our
    platform programmatically using the REST API. Our API allows developers to
    access various resources on our platform.
servers:
  -
    url: https://www.jpn-cards.com
    description: Live
paths:
  /card/id={id}:
    get:
      deprecated: true
      summary: Get a card
      operationId: getCard
      description: Get a single card's information based on its unique identifier.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PokemonCard'
      tags:
        - Cards
      parameters:
        - name: id
          in: path
          description: The id of the card.
          required: true
          example: 267
          schema:
            type: integer
  /card/?name={name}&set_id={set_id}&illustrator={illustrator}&type={type}&p_no={p_no}:
    get:
      deprecated: true
      summary: Get multiple cards
      operationId: getMultipleCards
      description: >-
        Get one or more cards based on more broad metadata.
        For values with spaces or other special characters in them, you're able to just pass it in normally or URL-encoded. For example, the following queries will return the same data.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PokemonCard'
      tags:
        - Cards
      parameters:
        - name: name
          in: path
          description: string name of the card
          required: false
          example: "Clefable"
          schema:
            type: string
        - name: set_id
          in: path
          description: 	integer id of the set the card is in
          required: false
          example: 10
          schema:
            type: integer
        - name: illustrator
          in: path
          description: string name of the illustrator/artist
          required: false
          example: "Shigenori%20Negishi"
          schema:
            type: string
        - name: type
          in: path
          description: the pokemon's type
          required: false
          example: "Fighting"
          schema:
            type: string
        - name: p_no
          in: path
          description: string printed number
          required: false
          example: "20"
          schema:
            type: string
  /set/{id}:
    get:
      deprecated: true
      summary: Get a set
      operationId: getSet
      description: Get a single set's information based on its unique identifier.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PokemonSet'
      tags:
        - Set
      parameters:
        - name: id
          in: path
          description: The id of the set.
          required: true
          example: 1
          schema:
            type: integer
  /set:
    get:
      deprecated: true
      summary: Get all sets
      operationId: getSets
      description: Get all sets and their information.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PokemonSet'
      tags:
        - Set
components:
  schemas:
    PokemonCard:
      type: object
      properties:
        id:
          type: integer
          example: 267
        setId:
          type: integer
          example: 4
        name:
          type: string
          example: "Eelektross"
          description: "The name of the card."
        sequenceNumber:
          type: integer
          example: 34
          description: "The sequential number of the card (applicable to Secret Rares)."
        printedNumber:
          type: string
          example: "34"
          description: "The number printed on the card, will be the same as sequenceNumber almost always. Is relevant for Promotional cards such as SWSH001"
        imageUrl:
          type: string
          format: url
          example: "https://content.tcgcollector.com/content/images/c9/79/fd/c979fde3902d4f4bf01de14245acd37f8bf2949fba61265f3950f0b7a22a6988.jpg"
          description: "The url pointing to the card's image. If there is no card image, then this will instead point to https://assets.tcgcollector.com/build/images/default-card-image.789f6232.png."
        hp:
          type: integer
          example: 160
          description: "The amount of HP the card has. If it does not have hp, then the value will be -1."
        evolvesFrom:
          type: string
          example: "Eelektrik"
          description: "If the card evolves from another card, this field will denote the name of the pre-evolution."
        effect:
          type: string
          example: "None"
          description: "Describes the card's effect. Mainly for Trainers and Special Energies."
        attacks:
          type: string
          example: "Lightning/Upper Shock/40\r\nIf this Pokémon evolved from Eelektrik during this turn, your opponent`s Active Pokémon is now Paralyzed.\r\nLightning-Colorless-Colorless/Wild Charge/160\r\nThis Pokémon also does 30 damage to itself."
          description: "Unparsed string describing all attacks the card has. Includes energy cost, attack name, attack damage, and any description or further effects."
        rules:
          type: string
          example: "None"
          description: "Describes rules the card is bound to. Mainly for cards with a Rule Box and certain Trainers."
        weakness:
          type: string
          example: "Fighting"
          description: "The type of energy the card is weak to. Does not include weakness modifier, only the type."
        resistance:
          type: string
          example: "None"
          description: "The type of energy the card is resistant to. Does not include resistance modifier, only the type."
        retreatCost:
          type: string
          example: "Colorless-Colorless-Colorless"
          description: "The amount of energy required to retreat."
        cardType:
          type: string
          example: "Pokémon"
          description: "The subset that the card falls into. For example, Single Strike Pokemon, Pokemon VMAX, etc."
        rarity:
          type: string
          example: "U"
          description: "The rarity of the card."
        cardFormat:
          type: string
          example: "None"
        illustrator:
          type: string
          example: "OKACHEKE"
          description: "The card art's illustrator."
        cardUrl:
          type: string
          format: url
          example: "https://www.tcgcollector.com/cards/34489/eelektross-eevee-heroes-034-069"
          description: "The URL which leads to the original card URL data."
        setName:
          type: string
          example: "Eevee Heroes"
          description: "The name of the set which the card belongs to."
        type:
          type: string
          example: "Lightning"
          description: "The energy type the card is."
    PokemonSet:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Blue Sky Stream"
          description: "The name of the set."
        year:
          type: string
          example: "None"
          description: "The year the set was released."
        total:
          type: integer
          example: 90
          description: "The total number of cards in the set."
        printedTotal:
          type: integer
          example: 67
          description: "The number of cards in the set that is printed on the card. This differs from the set's total in sets with Secret Rare cards."
        language:
          type: string
          example: "JPN"
          description: "The language that the cards in the set are printed in."
        setUrl:
          type: string
          format: "url"
          example: "https://www.tcgcollector.com/cards/jp/blue-sky-stream"
          description: "The URL to a page which has more information about the set."
        shorthand:
          type: string
          example: "s7r"
          description: "The shorthand code for the set."
        image:
          type: string
          format: "url"
          example: "https://content.tcgcollector.com/content/images/a3/cc/27/a3cc27411c1f1b89728a129ccc1ffcbc2a698855b5966375ce61a0298c77df48.png"
          description: "A URL to the official set's image."
tags:
  - name: Cards
    description: >-
      All card related API endpoints
  - name: Sets
    description: >-
      All set related API endpoints    
